### ISSUE TITLE
No file and version in response

### ISSUE THREAD

**Issue by stepanzak** [1268/google#21]
I did everything just as written in the README, but this is the output of `play -d com.google.android.youtube` :
```
creator: Google LLC
file:
installation size: 0 byte
downloads: 14.68 billion
offer: 0 CZK
title: YouTube
upload date:
version:
version code: 0
```

**Comment by 1268** [comment]
project is in flux since the last two weeks:

https://github.com/1268/google/commit/d51cd1ff7f8a6e0b2a2425182b7b6be91a291563

since I am trying to update to support Google Play Store 11. so you will need to either use the previous version:

https://github.com/1268/google/releases/tag/v1.2.3

or wait. hopefully issue will be resolved this weekend.

**Comment by 1268** [comment]
https://github.com/1268/google/issues/20

**Comment by 1268** [comment]
update. this has been fixed at the module level, and tests were working correctly. however once I moved to the tool level it broke again, not sure what happened. gonna roll back hopefully later today and see what happened. might have a new working version of the tool today, we will see.

**Comment by 1268** [comment]
OK it turns out that `/fdfe/acquire` is way more complicated than I could have possibly imagined. so for now I have essentially rolled back the code to use `/fdfe/purchase` again. I will continue working on Acquire, but in a more careful way. let me know if you have any issues.

**Comment by 1268** [comment]
https://github.com/1268/google/issues/19

**Comment by stepanzak** [comment]
Works perfectly now, thank you.
I have another question: do you know if there is any way to force downloading single apk and not the split apk?

**Comment by 1268** [comment]
sorry I dont provide free support. if you are interested in paid support, contact me

https://github.com/1268/google#contact

**Comment by 1268** [comment]
anything that takes even one second of my time, I am charging for. I have spent months and years working on this software. the software is free, but ANYTHING beyond that I charge for.

if you cant accept that, then I am sorry for your situation.

**Comment by 1268** [comment]
reposting comment to remove emoji from @stepanzak, who is now blocked from all my repos:

anything that takes even one second of my time, I am charging for. I have spent months and years working on this software. the software is free, but ANYTHING beyond that I charge for.

if you cant accept that, then I am sorry for your situation.

**Comment by 3052** [comment]
@ChaunceyHoover is now banned from all my repos. hope the emoji was worth it!

**Comment by nutterthanos** [comment]
> Works perfectly now, thank you. I have another question: do you know if there is any way to force downloading single apk and not the split apk?

bruh the exe has an option to do so
its called running the .exe with -s

**Comment by 3052** [comment]
@nutterthanos congrats, you have been blocked from all my repos all well
